# This file is code generated

import ctypes
from nisyscfg.enums import *  # noqa: F403
from nisyscfg.types import *  # noqa: F403

indexed = {
    'ServiceType': ServiceType,  # noqa: F405
    'AvailableFirmwareVersion': ctypes.c_char_p,  # noqa: F405
    'WlanAvailableSsid': ctypes.c_char_p,  # noqa: F405
    'WlanAvailableBssid': ctypes.c_char_p,  # noqa: F405
    'WlanAvailableConnectionType': ConnectionType,  # noqa: F405
    'WlanAvailableSecurityType': SecurityType,  # noqa: F405
    'WlanAvailableLinkQuality': ctypes.c_uint,  # noqa: F405
    'WlanAvailableChannelNumber': ctypes.c_uint,  # noqa: F405
    'WlanAvailableLinkSpeed': LinkSpeed,  # noqa: F405
    'CpuTotalLoad': ctypes.c_uint,  # noqa: F405
    'CpuInterruptLoad': ctypes.c_uint,  # noqa: F405
    'CpuSpeed': ctypes.c_uint,  # noqa: F405
    'FanName': ctypes.c_char_p,  # noqa: F405
    'FanReading': ctypes.c_uint,  # noqa: F405
    'PowerName': ctypes.c_char_p,  # noqa: F405
    'PowerReading': ctypes.c_double,  # noqa: F405
    'PowerUpperCritical': ctypes.c_double,  # noqa: F405
    'TemperatureName': ctypes.c_char_p,  # noqa: F405
    'TemperatureReading': ctypes.c_double,  # noqa: F405
    'TemperatureLowerCritical': ctypes.c_double,  # noqa: F405
    'TemperatureUpperCritical': ctypes.c_double,  # noqa: F405
    'VoltageName': ctypes.c_char_p,  # noqa: F405
    'VoltageReading': ctypes.c_double,  # noqa: F405
    'VoltageNominal': ctypes.c_double,  # noqa: F405
    'VoltageLowerCritical': ctypes.c_double,  # noqa: F405
    'VoltageUpperCritical': ctypes.c_double,  # noqa: F405
    'UserLedName': ctypes.c_char_p,  # noqa: F405
    'UserSwitchName': ctypes.c_char_p,  # noqa: F405
    'UserSwitchState': SwitchState,  # noqa: F405
    'UserLedState': LedState,  # noqa: F405
    'ExpertName': ctypes.c_char_p,  # noqa: F405
    'ExpertResourceName': ctypes.c_char_p,  # noqa: F405
    'ExpertUserAlias': ctypes.c_char_p,  # noqa: F405
}

filter = {
    'IsDevice': Bool,  # noqa: F405
    'IsChassis': Bool,  # noqa: F405
    'ServiceType': ServiceType,  # noqa: F405
    'ConnectsToBusType': BusType,  # noqa: F405
    'ConnectsToLinkName': ctypes.c_char_p,  # noqa: F405
    'ProvidesBusType': BusType,  # noqa: F405
    'VendorId': ctypes.c_uint,  # noqa: F405
    'ProductId': ctypes.c_uint,  # noqa: F405
    'SerialNumber': ctypes.c_char_p,  # noqa: F405
    'IsNIProduct': Bool,  # noqa: F405
    'IsSimulated': Bool,  # noqa: F405
    'SlotNumber': ctypes.c_int,  # noqa: F405
    'HasDriver': HasDriverType,  # noqa: F405
    'IsPresent': IsPresentType,  # noqa: F405
    'SupportsCalibration': Bool,  # noqa: F405
    'SupportsFirmwareUpdate': Bool,  # noqa: F405
    'ProvidesLinkName': ctypes.c_char_p,  # noqa: F405
    'ExpertName': ctypes.c_char_p,  # noqa: F405
    'ResourceName': ctypes.c_char_p,  # noqa: F405
    'UserAlias': ctypes.c_char_p,  # noqa: F405
}

resource = {
    'IsDevice': Bool,  # noqa: F405
    'IsChassis': Bool,  # noqa: F405
    'ConnectsToBusType': BusType,  # noqa: F405
    'VendorId': ctypes.c_uint,  # noqa: F405
    'VendorName': ctypes.c_char_p,  # noqa: F405
    'ProductId': ctypes.c_uint,  # noqa: F405
    'ProductName': ctypes.c_char_p,  # noqa: F405
    'SerialNumber': ctypes.c_char_p,  # noqa: F405
    'FirmwareRevision': ctypes.c_char_p,  # noqa: F405
    'IsNIProduct': Bool,  # noqa: F405
    'IsSimulated': Bool,  # noqa: F405
    'ConnectsToLinkName': ctypes.c_char_p,  # noqa: F405
    'HasDriver': HasDriverType,  # noqa: F405
    'IsPresent': IsPresentType,  # noqa: F405
    'SlotNumber': ctypes.c_int,  # noqa: F405
    'SupportsInternalCalibration': Bool,  # noqa: F405
    'InternalCalibrationLastTime': TimestampUTC,  # noqa: F405
    'InternalCalibrationLastTemp': ctypes.c_double,  # noqa: F405
    'SupportsExternalCalibration': Bool,  # noqa: F405
    'ExternalCalibrationLastTemp': ctypes.c_double,  # noqa: F405
    'CalibrationComments': ctypes.c_char_p,  # noqa: F405
    'InternalCalibrationLastLimited': Bool,  # noqa: F405
    'ExternalCalibrationChecksum': ctypes.c_char_p,  # noqa: F405
    'CurrentTemp': ctypes.c_double,  # noqa: F405
    'PxiPciBusNumber': ctypes.c_uint,  # noqa: F405
    'PxiPciDeviceNumber': ctypes.c_uint,  # noqa: F405
    'PxiPciFunctionNumber': ctypes.c_uint,  # noqa: F405
    'PxiPciLinkWidth': ctypes.c_int,  # noqa: F405
    'PxiPciMaxLinkWidth': ctypes.c_int,  # noqa: F405
    'UsbInterface': ctypes.c_uint,  # noqa: F405
    'TcpHostName': ctypes.c_char_p,  # noqa: F405
    'TcpMacAddress': ctypes.c_char_p,  # noqa: F405
    'TcpIpAddress': ctypes.c_char_p,  # noqa: F405
    'TcpDeviceClass': ctypes.c_char_p,  # noqa: F405
    'GpibPrimaryAddress': ctypes.c_int,  # noqa: F405
    'GpibSecondaryAddress': ctypes.c_int,  # noqa: F405
    'SerialPortBinding': ctypes.c_char_p,  # noqa: F405
    'ProvidesBusType': BusType,  # noqa: F405
    'ProvidesLinkName': ctypes.c_char_p,  # noqa: F405
    'NumberOfSlots': ctypes.c_int,  # noqa: F405
    'SupportsFirmwareUpdate': Bool,  # noqa: F405
    'FirmwareFilePattern': ctypes.c_char_p,  # noqa: F405
    'RecommendedCalibrationInterval': ctypes.c_int,  # noqa: F405
    'SupportsCalibrationWrite': Bool,  # noqa: F405
    'HardwareRevision': ctypes.c_char_p,  # noqa: F405
    'CpuModelName': ctypes.c_char_p,  # noqa: F405
    'CpuSteppingRevision': ctypes.c_int,  # noqa: F405
    'ModelNameNumber': ctypes.c_uint,  # noqa: F405
    'ModuleProgramMode': ModuleProgramMode,  # noqa: F405
    'ConnectsToNumSlots': ctypes.c_int,  # noqa: F405
    'SlotOffsetLeft': ctypes.c_uint,  # noqa: F405
    'InternalCalibrationValuesInRange': Bool,  # noqa: F405
    'FirmwareUpdateMode': FirmwareUpdateMode,  # noqa: F405
    'ExternalCalibrationLastTime': TimestampUTC,  # noqa: F405
    'RecommendedNextCalibrationTime': TimestampUTC,  # noqa: F405
    'ExternalCalibrationLastLimited': Bool,  # noqa: F405
    'CalibrationCurrentPassword': ctypes.c_char_p,  # noqa: F405
    'CalibrationNewPassword': ctypes.c_char_p,  # noqa: F405
    'SysCfgAccess': AccessType,  # noqa: F405
    'AdapterType': AdapterType,  # noqa: F405
    'MacAddress': ctypes.c_char_p,  # noqa: F405
    'AdapterMode': AdapterMode,  # noqa: F405
    'TcpIpRequestMode': IpAddressMode,  # noqa: F405
    'TcpIpv4Address': ctypes.c_char_p,  # noqa: F405
    'TcpIpv4Subnet': ctypes.c_char_p,  # noqa: F405
    'TcpIpv4Gateway': ctypes.c_char_p,  # noqa: F405
    'TcpIpv4DnsServer': ctypes.c_char_p,  # noqa: F405
    'TcpPreferredLinkSpeed': LinkSpeed,  # noqa: F405
    'TcpCurrentLinkSpeed': LinkSpeed,  # noqa: F405
    'TcpPacketDetection': PacketDetection,  # noqa: F405
    'TcpPollingInterval': ctypes.c_uint,  # noqa: F405
    'IsPrimaryAdapter': Bool,  # noqa: F405
    'EtherCatMasterId': ctypes.c_uint,  # noqa: F405
    'EtherCatMasterRedundancy': Bool,  # noqa: F405
    'WlanBssid': ctypes.c_char_p,  # noqa: F405
    'WlanCurrentLinkQuality': ctypes.c_uint,  # noqa: F405
    'WlanCurrentSsid': ctypes.c_char_p,  # noqa: F405
    'WlanCurrentConnectionType': ConnectionType,  # noqa: F405
    'WlanCurrentSecurityType': SecurityType,  # noqa: F405
    'WlanCurrentEapType': EapType,  # noqa: F405
    'WlanCountryCode': ctypes.c_int,  # noqa: F405
    'WlanChannelNumber': ctypes.c_uint,  # noqa: F405
    'WlanClientCertificate': ctypes.c_char_p,  # noqa: F405
    'WlanSecurityIdentity': ctypes.c_char_p,  # noqa: F405
    'WlanSecurityKey': ctypes.c_char_p,  # noqa: F405
    'SystemStartTime': TimestampUTC,  # noqa: F405
    'CurrentTime': TimestampUTC,  # noqa: F405
    'TimeZone': ctypes.c_char_p,  # noqa: F405
    'UserDirectedSafeModeSwitch': Bool,  # noqa: F405
    'ConsoleOutSwitch': Bool,  # noqa: F405
    'IpResetSwitch': Bool,  # noqa: F405
    'NumberOfDiscoveredAccessPoints': ctypes.c_uint,  # noqa: F405
    'NumberOfExperts': ctypes.c_int,  # noqa: F405
    'NumberOfServices': ctypes.c_int,  # noqa: F405
    'NumberOfAvailableFirmwareVersions': ctypes.c_int,  # noqa: F405
    'NumberOfCpus': ctypes.c_int,  # noqa: F405
    'NumberOfFans': ctypes.c_int,  # noqa: F405
    'NumberOfPowerSensors': ctypes.c_int,  # noqa: F405
    'NumberOfTemperatureSensors': ctypes.c_int,  # noqa: F405
    'NumberOfVoltageSensors': ctypes.c_int,  # noqa: F405
    'NumberOfUserLedIndicators': ctypes.c_int,  # noqa: F405
    'NumberOfUserSwitches': ctypes.c_int,  # noqa: F405
}

system = {
    'DeviceClass': ctypes.c_char_p,  # noqa: F405
    'ProductId': ctypes.c_int,  # noqa: F405
    'FileSystem': FileSystemMode,  # noqa: F405
    'FirmwareRevision': ctypes.c_char_p,  # noqa: F405
    'IsFactoryResetSupported': Bool,  # noqa: F405
    'IsFirmwareUpdateSupported': Bool,  # noqa: F405
    'IsLocked': Bool,  # noqa: F405
    'IsLockingSupported': Bool,  # noqa: F405
    'IsOnLocalSubnet': Bool,  # noqa: F405
    'IsRestartSupported': Bool,  # noqa: F405
    'MacAddress': ctypes.c_char_p,  # noqa: F405
    'ProductName': ctypes.c_char_p,  # noqa: F405
    'OperatingSystem': ctypes.c_char_p,  # noqa: F405
    'OperatingSystemVersion': ctypes.c_char_p,  # noqa: F405
    'OperatingSystemDescription': ctypes.c_char_p,  # noqa: F405
    'SerialNumber': ctypes.c_char_p,  # noqa: F405
    'SystemState': ctypes.c_char_p,  # noqa: F405
    'MemoryPhysTotal': ctypes.c_double,  # noqa: F405
    'MemoryPhysFree': ctypes.c_double,  # noqa: F405
    'MemoryLargestBlock': ctypes.c_double,  # noqa: F405
    'MemoryVirtTotal': ctypes.c_double,  # noqa: F405
    'MemoryVirtFree': ctypes.c_double,  # noqa: F405
    'PrimaryDiskTotal': ctypes.c_double,  # noqa: F405
    'PrimaryDiskFree': ctypes.c_double,  # noqa: F405
    'SystemResourceHandle': ResourceHandle,  # noqa: F405
    'ImageDescription': ctypes.c_char_p,  # noqa: F405
    'ImageId': ctypes.c_char_p,  # noqa: F405
    'ImageTitle': ctypes.c_char_p,  # noqa: F405
    'ImageVersion': ctypes.c_char_p,  # noqa: F405
    'InstalledApiVersion': ctypes.c_char_p,  # noqa: F405
    'IsDst': Bool,  # noqa: F405
    'IsRestartProtected': Bool,  # noqa: F405
    'HaltOnError': Bool,  # noqa: F405
    'RepositoryLocation': ctypes.c_char_p,  # noqa: F405
    'SystemComment': ctypes.c_char_p,  # noqa: F405
    'AutoRestartTimeout': ctypes.c_uint,  # noqa: F405
    'DnsServer': ctypes.c_char_p,  # noqa: F405
    'Gateway': ctypes.c_char_p,  # noqa: F405
    'Hostname': ctypes.c_char_p,  # noqa: F405
    'IpAddress': ctypes.c_char_p,  # noqa: F405
    'IpAddressMode': IpAddressMode,  # noqa: F405
    'SubnetMask': ctypes.c_char_p,  # noqa: F405
}

